baseURL = 'https://baumert.me/'
languageCode = 'en-us'
copyright = "© Niklas Baumert"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Niklas Baumert"

[params]
  defaultTheme = "dark"
  description = "A simple gallery of photos by Niklas Baumert"
  title = "Photography by Niklas Baumert"
  [params.author]
    email = "gallery@baumert.me"
    name = "Niklas Baumert"
  [params.socialIcons]
    # facebook = "https://www.facebook.com/"
    # instagram = "https://www.instagram.com/"
    github = "https://github.com/baumertn/"
    # youtube = "https://www.youtube.com/"
    email = "mailto:gallery@baumert.me"
    website = "https://baumert.me"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://mixcloud.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  # [[menu.footer]]
  #   name = "GitHub"
  #   url = "https://github.com/nicokaiser/hugo-theme-gallery/"
  #   weight = 3

[services]
  [services.rss]
    limit = 100
